import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="navbar bg-slate-700">
          <Link className="btn btn-ghost text-xl mx-[16px] text-white" href="/">Home</Link>
          <Link className="btn btn-ghost text-xl mx-[16px] text-white" href="/gallery">Gallery</Link>
          <Link className="btn btn-ghost text-xl mx-[16px] text-white" href="/viewerOptions">Viewer</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
